version: '3'

services:
  # app:
  #   build: .
  #   container_name: felix-api-container
  #   hostname: felix-api
  #   command: sh prisma.sh
  #   depends_on:
  #     - db
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  db:
    image: mysql:8
    restart: always
    container_name: felix-db-container
    hostname: felix-db
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

volumes:
  db-store:
