# Generated by Django 4.2.2 on 2023-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_test',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('BookingDate', models.DateTimeField()),
            ],
        ),
    ]
